<!DOCTYPE html>
<!--
El uso de try/catch es fundamental para manejar errores en bloques de código críticos, 
permitiendo que el programa continúe ejecutándose de manera controlada incluso si ocurre un error. 
Es especialmente útil en operaciones que pueden fallar, como llamadas a APIs, operaciones de lectura/escritura de archivos, 
o cualquier otra operación que dependa de factores externos.

El uso de async/await simplifica el manejo de promesas en JavaScript, 
haciendo que el código asíncrono se vea y se comporte de manera más similar al código síncrono. 
Es importante usar async/await cuando se desea escribir código asíncrono de manera más clara y legible, 
especialmente en secuencias de operaciones asíncronas donde el orden de ejecución es crucial.

Las promesas en JavaScript se utilizan para manejar operaciones asíncronas de una manera más manejable y legible. Antes de las promesas, el manejo de operaciones asíncronas se hacía principalmente con callbacks, lo que podía llevar a un código difícil de leer y mantener, conocido como "callback hell".

Las promesas permiten encadenar operaciones asíncronas y manejar errores de una manera más clara y estructurada. Con el uso de `async` y `await`, el código asíncrono se puede escribir de manera similar al código síncrono, lo que mejora la legibilidad y facilita el manejo de errores.

En el ejemplo proporcionado, se utilizan promesas para simular la descarga de clientes y pedidos, y `async/await` para esperar a que estas operaciones se completen antes de continuar con la ejecución del código.
-->

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //función base
        function descargarClientes(){
            return new Promise((resolve,reject)=>{
                const error= false;
                setTimeout(()=>{
                    if(!error){
                        resolve('El listado de clientes se descargó correctamente');
                    }else{
                        reject('No se pudo descargar el listado de clientes');
                    }
                },3000);
            })
        }
        //Try catch con un asynawait.Probamos a escribir las funciones mediante expresión y definición
            // Por definición
        async function ejecutar(){
            try{
                console.log(1+1)
                const respuesta= await descargarClientes() // ahora si espera hasta la promesa por eso imprime solo el console de arriba
                console.log(2+2)
                console.log(respuesta)
            }catch(error){
                console.log(error)
            }
        }
        ejecutar()
            // Por expresión
        const ejemplo= async ()=>{
            try{
                console.log(1+1)
                const respuesta= await descargarClientes() // ahora si espera hasta la promesa por eso imprime solo el console de arriba
                console.log(2+2)
                console.log(respuesta)
            }catch(error){
                console.log(error)
            }
        }

        //Nuevo ejemplo

        function descargarNuevosClientes() {
            return new Promise((resolve, reject) => {
            const error = false;
            setTimeout(() => {
                if (!error) {
                resolve('Los clientes fueron descargados');
                } else {
                reject('No se pudo descargar el listado de nuevos clientes');
                }
            }, 5000);
            });
        }

        function descargarNuevosPedidos() {
            return new Promise((resolve, reject) => {
            const error = false;
            setTimeout(() => {
                if (!error) {
                resolve('Descargando pedidos');
                } else {
                reject('No se pudo descargar el listado de nuevos pedidos');
                }
            }, 3000);
            });
        }
        const app= async () => {
            try {
            const clientes = await descargarNuevosClientes();//hasta que no termine la primera promesa no pasamos a la segunda de abajo
            console.log(clientes);
            const pedidos = await descargarNuevosPedidos();
            console.log(pedidos);
            } catch (error) {
            console.log(error);
            }
        }

        app();

        
    </script>
</body>
</html>